# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ardrone_gui.ui'
#
# Created: Sat Apr  1 17:15:01 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 704)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gb_basic = QtGui.QGroupBox(self.centralwidget)
        self.gb_basic.setGeometry(QtCore.QRect(20, 10, 191, 161))
        self.gb_basic.setObjectName("gb_basic")
        self.layoutWidget = QtGui.QWidget(self.gb_basic)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_takeoff = QtGui.QPushButton(self.layoutWidget)
        self.btn_takeoff.setObjectName("btn_takeoff")
        self.gridLayout.addWidget(self.btn_takeoff, 0, 0, 1, 2)
        self.btn_land = QtGui.QPushButton(self.layoutWidget)
        self.btn_land.setObjectName("btn_land")
        self.gridLayout.addWidget(self.btn_land, 0, 2, 1, 1)
        self.btn_emergency = QtGui.QPushButton(self.layoutWidget)
        self.btn_emergency.setObjectName("btn_emergency")
        self.gridLayout.addWidget(self.btn_emergency, 1, 0, 1, 3)
        self.btn_switchmode = QtGui.QPushButton(self.layoutWidget)
        self.btn_switchmode.setObjectName("btn_switchmode")
        self.gridLayout.addWidget(self.btn_switchmode, 2, 0, 1, 1)
        self.lb_mode = QtGui.QLabel(self.layoutWidget)
        self.lb_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_mode.setObjectName("lb_mode")
        self.gridLayout.addWidget(self.lb_mode, 2, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 180, 331, 121))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 30, 251, 78))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 2, 1, 1)
        self.lb_vrpn_oz = QtGui.QLabel(self.layoutWidget1)
        self.lb_vrpn_oz.setObjectName("lb_vrpn_oz")
        self.gridLayout_3.addWidget(self.lb_vrpn_oz, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.lb_vrpn_px = QtGui.QLabel(self.layoutWidget1)
        self.lb_vrpn_px.setObjectName("lb_vrpn_px")
        self.gridLayout_3.addWidget(self.lb_vrpn_px, 0, 1, 1, 1)
        self.lb_vrpn_ox = QtGui.QLabel(self.layoutWidget1)
        self.lb_vrpn_ox.setObjectName("lb_vrpn_ox")
        self.gridLayout_3.addWidget(self.lb_vrpn_ox, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.lb_vrpn_py = QtGui.QLabel(self.layoutWidget1)
        self.lb_vrpn_py.setObjectName("lb_vrpn_py")
        self.gridLayout_3.addWidget(self.lb_vrpn_py, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.lb_vrpn_oy = QtGui.QLabel(self.layoutWidget1)
        self.lb_vrpn_oy.setObjectName("lb_vrpn_oy")
        self.gridLayout_3.addWidget(self.lb_vrpn_oy, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.lb_vrpn_pz = QtGui.QLabel(self.layoutWidget1)
        self.lb_vrpn_pz.setObjectName("lb_vrpn_pz")
        self.gridLayout_3.addWidget(self.lb_vrpn_pz, 2, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 250, 331, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 311, 98))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.layoutWidget2)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_4.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_4.addWidget(self.spinBox, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.horizontalSlider_2 = QtGui.QSlider(self.layoutWidget2)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_4.addWidget(self.horizontalSlider_2, 1, 1, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_4.addWidget(self.spinBox_2, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.horizontalSlider_3 = QtGui.QSlider(self.layoutWidget2)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout_4.addWidget(self.horizontalSlider_3, 2, 1, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_4.addWidget(self.spinBox_3, 2, 2, 1, 1)
        self.gridLayout_4.setColumnMinimumWidth(1, 200)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 80, 331, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(100, 60, 110, 32))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(52, 30, 271, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sb_hoverpos_x = QtGui.QSpinBox(self.layoutWidget3)
        self.sb_hoverpos_x.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sb_hoverpos_x.setMinimum(-5000)
        self.sb_hoverpos_x.setMaximum(5000)
        self.sb_hoverpos_x.setSingleStep(1)
        self.sb_hoverpos_x.setProperty("value", -1500)
        self.sb_hoverpos_x.setObjectName("sb_hoverpos_x")
        self.gridLayout_5.addWidget(self.sb_hoverpos_x, 0, 0, 1, 1)
        self.sb_hoverpos_y = QtGui.QSpinBox(self.layoutWidget3)
        self.sb_hoverpos_y.setMinimum(-5000)
        self.sb_hoverpos_y.setMaximum(5000)
        self.sb_hoverpos_y.setProperty("value", 500)
        self.sb_hoverpos_y.setObjectName("sb_hoverpos_y")
        self.gridLayout_5.addWidget(self.sb_hoverpos_y, 0, 1, 1, 1)
        self.sb_hoverpos_z = QtGui.QSpinBox(self.layoutWidget3)
        self.sb_hoverpos_z.setMinimum(-5000)
        self.sb_hoverpos_z.setMaximum(5000)
        self.sb_hoverpos_z.setProperty("value", 1500)
        self.sb_hoverpos_z.setObjectName("sb_hoverpos_z")
        self.gridLayout_5.addWidget(self.sb_hoverpos_z, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(380, 10, 321, 71))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"color:rgb(252, 0, 6)}")
        self.label_15.setFrameShape(QtGui.QFrame.Box)
        self.label_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_15.setLineWidth(1)
        self.label_15.setMidLineWidth(1)
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(130, 440, 331, 211))
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("QLabel{background:rgb(0, 0, 0);color:rgb(255,255,255)}")
        self.label_16.setFrameShape(QtGui.QFrame.Panel)
        self.label_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_16.setLineWidth(4)
        self.label_16.setMidLineWidth(3)
        self.label_16.setObjectName("label_16")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 630, 110, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(220, 30, 130, 124))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lcdNumber_roll = QtGui.QLCDNumber(self.layoutWidget4)
        self.lcdNumber_roll.setObjectName("lcdNumber_roll")
        self.gridLayout_2.addWidget(self.lcdNumber_roll, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lcdNumber_pitch = QtGui.QLCDNumber(self.layoutWidget4)
        self.lcdNumber_pitch.setObjectName("lcdNumber_pitch")
        self.gridLayout_2.addWidget(self.lcdNumber_pitch, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lcdNumber_yaw = QtGui.QLCDNumber(self.layoutWidget4)
        self.lcdNumber_yaw.setObjectName("lcdNumber_yaw")
        self.gridLayout_2.addWidget(self.lcdNumber_yaw, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.lcdNumber_throttle = QtGui.QLCDNumber(self.layoutWidget4)
        self.lcdNumber_throttle.setObjectName("lcdNumber_throttle")
        self.gridLayout_2.addWidget(self.lcdNumber_throttle, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 300, 331, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(40, 30, 251, 78))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_34 = QtGui.QLabel(self.layoutWidget_4)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_8.addWidget(self.label_34, 2, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget_4)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 1, 0, 1, 1)
        self.lb_navdata_vy = QtGui.QLabel(self.layoutWidget_4)
        self.lb_navdata_vy.setObjectName("lb_navdata_vy")
        self.gridLayout_8.addWidget(self.lb_navdata_vy, 1, 1, 1, 1)
        self.lb_navdata_vx = QtGui.QLabel(self.layoutWidget_4)
        self.lb_navdata_vx.setObjectName("lb_navdata_vx")
        self.gridLayout_8.addWidget(self.lb_navdata_vx, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget_4)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 0, 0, 1, 1)
        self.lb_navdata_vz = QtGui.QLabel(self.layoutWidget_4)
        self.lb_navdata_vz.setObjectName("lb_navdata_vz")
        self.gridLayout_8.addWidget(self.lb_navdata_vz, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Drone Controller GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_basic.setTitle(QtGui.QApplication.translate("MainWindow", "Drone Control", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_takeoff.setText(QtGui.QApplication.translate("MainWindow", "Takeoff", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_land.setText(QtGui.QApplication.translate("MainWindow", "Land", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_emergency.setText(QtGui.QApplication.translate("MainWindow", "Emergency", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_switchmode.setText(QtGui.QApplication.translate("MainWindow", "M/A", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_mode.setText(QtGui.QApplication.translate("MainWindow", "AUTOMATIC", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "VRPN data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "roll:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "yaw:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_vrpn_oz.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_vrpn_px.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_vrpn_ox.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_vrpn_py.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "pitch:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_vrpn_oy.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "z:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_vrpn_pz.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "PID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Kp:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Ki:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Kd:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Mission Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Pos:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "GOTO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "WARNING: You should be fully aware of what you are doing when changing the parametres and command. Misoperation may leads to serious injury or death.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "VIDEO", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "SwitchCam", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Pitch:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Yaw:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Throttle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Roll:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Navdata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "vz:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "vy:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_navdata_vy.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_navdata_vx.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "vx:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_navdata_vz.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))

